apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: media-center-secrets
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-secret-store
    kind: ClusterSecretStore
  target:
    name: media-center-secrets
    creationPolicy: Owner
  data:
    - secretKey: JELLYFIN_URL
      remoteRef:
        key: secret/k8s/media/jellyfin
        property: url
    - secretKey: JELLYFIN_API_KEY
      remoteRef:
        key: secret/k8s/media/jellyfin
        property: api_key
    - secretKey: SONARR_URL
      remoteRef:
        key: secret/k8s/media/sonarr
        property: url
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: secret/k8s/media/sonarr
        property: api_key
    - secretKey: RADARR_URL
      remoteRef:
        key: secret/k8s/media/radarr
        property: url
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: secret/k8s/media/radarr
        property: api_key
