apiVersion: v1
kind: Service
metadata:
  name: media-center-dashboard
  namespace: media
spec:
  selector:
    app: media-center-dashboard
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
